### ISSUE TITLE
v0.11.4 for opal-cdn

### ISSUE THREAD

**Issue by nwtgck** [opal/opal-cdn#29]
Hi, developers!

Opal v0.11.4 has been released: https://github.com/opal/opal/releases/tag/v0.11.4.
Do you have a plan to release opal-cdn for v0.11.4?

I was wondering if you could tell me how to build `opal.min.js` or `opal-parser.min.js` by my own from [opal/opal](https://github.com/opal/opal).

**Comment by ggrossetie** [comment]
Hello @nwtgck,

You can follow the "Updating" guide on the README: https://github.com/opal/opal-cdn/blob/gh-pages/README.md#updating

If you are not a Ruby developer, I recommend to install `rvm` and `bundle`.

I'm using the following command to generate `opal.js`:

```
bundle exec rake dist
```

You should define the `DIR` to output the result in the desired directory.

You will also need Node.js and npm to install uglifyjs globally (otherwise the minification will failed).

Let me know if it's working on your machine.

**Comment by nwtgck** [comment]
@Mogztter Thank you very much. I'll try it and tell you!

**Comment by nwtgck** [comment]
I tried to do like the following.

```bash
# Clone opal not opal-cdn
git clone git@github.com:opal/opal.git
# Go to opal directory
cd opal
# Bundle install
bundle install
# Create js files
bundle exec rake dist DIR=cdn/opal/0.7.0.dev
```

Then, I got like the following files.

```
./opal
...
├── cdn
│   └── opal
│       └── 0.7.0.dev
│           ├── base64.js
│           ├── base64.min.js
│           ├── base64.min.js.gz
│           ├── benchmark.js
│           ├── benchmark.min.js
....
```

@Mogztter Thank you very much!

**Comment by ggrossetie** [comment]
The directory should be `0.11.4` but otherwise it looks good :+1:

Feel free to open a pull request to add the latest version. Don't forget to replace current with the latest version.

**Comment by elia** [comment]
side comment: We need to improve instructions or even better automate this stuff

Thanks @nwtgck !

**Comment by nwtgck** [comment]
@elia Automation is a very great idea!

**Comment by elia** [comment]
Fixed by https://github.com/opal/opal-cdn/commit/055dc2f933271a8ea27ab3b3ee1d393112cda769 and thanks for the PR! 👍👍👍
