### ISSUE TITLE
Please update opal-jquery and opal-browser CDNs

### ISSUE THREAD

**Issue by ylluminarious** [opal/opal-cdn#7]
If you take a look under [`external/0.6.2`](https://github.com/opal/opal-cdn/tree/gh-pages/external/0.6.2), you'll see that the opal-browser and opal-jquery CDNs are out of date. I've tried using them on an older project of mine, where they had worked in the past, and saw that everything is broken. The errors are coming from opal-browser and opal-jquery. Like I said, my project was working before using the opal-jquery and opal-browser CDNs, but it is now broken and the only thing that's changed is the version of Opal. Their outdated versions must be causing the problem, as the they are not only using old versions of themselves, but are also using an old version of Opal.

**Comment by ggrossetie** [comment]
What version of Opal, opal-jquery and opal-browser are you using ? How did you get this files (before using CDN version) ?

@elia How opal-browser is generated ? I guess that opal-jquery is generated from https://github.com/opal/opal-jquery but I didn't find the opal-browser repository...

Thanks

**Comment by elia** [comment]
@mogztter Opal browser is here https://github.com/opal/opal-browser

@ylluminarious stuff on the CDN is precompiled and precompiled code is not guaranteed to run between Opal version. That's why compiling locally is always the best option. 

That said now that 0.8 is out it's good to add updated versions for all the main libs.

**Comment by ggrossetie** [comment]
Argh mobile version of GitHub doesn't show all the repositories :(

Cool 0.8.0 is out!

Can I put opal-jquery and opal-browser directly into the corresponding
version to avoid an extra directory for each version (external/$version) ?

**Comment by elia** [comment]
I think it's better to keep the version part to clearly state which Opal version has been used to compile the external lib, which is also the Opal version with which the lib is expected to work.

**Comment by ggrossetie** [comment]
Sure but I just want to remove `opal/external/0.6.2` and put the files directly in `opal/0.6.2`.

**Comment by elia** [comment]
Oh I see, the only fear I have is name space clashes with either the lib files or the lib name.

**Comment by ggrossetie** [comment]
I can add a suffix to the lib name ext-opal-browser.js and ext-opal-jquery.js or a suffix ?
Or create the directory `external` inside the version ?
I just want to remove the duplication of the version because to avoid confusion and make it clear that you have to use the same version for core and libs.

(sorry for close/reopen, my fingers are too fat for the mobile version :smile:)

**Comment by Mogztter** [comment]
Hmmm just saw that the index page is broken (with v0.8.0): http://cdn.opalrb.org/
I tried to load `native` and `opal/parser` modules but that's not working:
```javascript
<script>
  Opal.load('native');
  Opal.load('opal/parser');
</script>
```

**Comment by elia** [comment]
👍🏼 for keeping "external" inside the version. Now that we're at how do you see renaming "external" into "gems"?

**Comment by ggrossetie** [comment]
I think "gems" is too specific to Ruby (and maybe misleading since we are
serving JavaScript files). What about "libs" or "extensions" ?
In my opinion, "modules" is too confusing because now everything is a
module in Opal.

**Comment by elia** [comment]
"libs" looks good to me 👍🏼

**Comment by elia** [comment]
Of course "external" is equally fine

(Also remember to keep the old external dir available)
